### ISSUE TITLE
Modernification Master Task

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#742]
Immutable.js's tools are behind the times and it is limiting progress on some of the top line goals.

This is a master task that details all the steps required to modernize the repository.
- [x] move the source for gh-pages into master branch (#741)
- [x] automatically deploy gh-pages when master pages src changes (a71d9b60f0944535c2b05c1dafb926833132473d)
- [x] use latest jest for tests
- [x] use eslint for linting (#1101)
- [x] improve strictness of lint rules (#1101)
- [x] run tests against latest versions of node (a91b5e7)
- [x] update to the latest version of typescript (#745)
- [x] use buble for ES6 -> ES3 compilation (#1102)
- [ ] remove usage of gulp in favor of npm scripts? (1b4166952995a7ceb898c254dfdc3b219210b597)
- [x] remove usage of grunt in favor of npm scripts (1b4166952995a7ceb898c254dfdc3b219210b597) (#1102)
- [x] include flow type definition file
- [ ] no longer check in distributed files (breaking change)
- [ ] move contrib to separate repository (breaking change)
- [x] setup yarn (#1100)
- [x] setup prettier (#1101)
- <s>move documentation generator source of truth to flow type + babel.</s> - Note, updated to latest TypeScript instead.

**Comment by umidbekkarimov** [comment]
I also suggest to add https://github.com/prettier/prettier and https://github.com/yarnpkg/yarn to the list

**Comment by umidbekkarimov** [comment]
As I said in https://github.com/facebook/immutable-js/pull/1096#issuecomment-284227352

> And first problem.
> 
> According to the spec - es6 classes can not be called as a functions.
> 
> Few solutions:
> 
> Make a breaking change and disalow var map = Map() syntax in favor of var map = new Map().
> Refactor all es6 classes to Function.prototype style.
> Keep using declassify (but first - need to fix it for latest rollup).

**Comment by leebyron** [comment]
Using `new` with collections is actually an anti pattern. They're designed to be used like the JS scalar types (Number, String) as just a callable function. 

That does mean the class syntax either needs to only ever be consumed by an off-spec transformer or it needs to be converted to use MapPrototype.method = function(){} or rely on Object.create's extra properties param or something like that

**Comment by leebyron** [comment]
I think it's safe to call this task done. There's always more modernization to be done, but this hits the major objectives.

Thanks so much for your help, @umidbekkarimov!

**Comment by umidbekkarimov** [comment]
@leebyron yep 👍 for docs need to update react, react-router and jump from gulp to webpack+webpack-dev-server. I guess it's `good first bug` for facebook juniors 😜
